project/__init__.py
from flask import Flask
from logging.handlers import RotatingFileHandler
import os
import logging
from flask.logging import default_handler


def create_app():
    # Create the Flask application
    app = Flask(__name__)

    # Configure the app
    config_type = os.getenv('CONFIG_TYPE', default='config.DevelopmentConfig')
    app.config.from_object(config_type)

    register_blueprints(app)
    configure_logging(app)
    register_app_callbacks(app)
    return app


def register_blueprints(app):
    # Import the blueprints
    from project.stocks import stocks_blueprint
    from project.users import users_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(stocks_blueprint)
    app.register_blueprint(users_blueprint, url_prefix='/users')


def configure_logging(app):
    # Logging Configuration
    file_handler = RotatingFileHandler('instance/flask-stock-portfolio.log',
                                       maxBytes=16384,
                                       backupCount=20)
    file_formatter = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(filename)s:%(lineno)d]')
    file_handler.setFormatter(file_formatter)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)

    # Remove the default logger configured by Flask
    app.logger.removeHandler(default_handler)

    app.logger.info('Starting the Flask Stock Portfolio App...')


def register_app_callbacks(app):
    @app.before_request
    def app_before_request():
        app.logger.info(
            'Calling before_request() for the Flask application...')

    @app.after_request
    def app_after_request(response):
        app.logger.info('Calling after_request() for the Flask application...')
        return response

    @app.teardown_request
    def app_teardown_request(error=None):
        app.logger.info(
            'Calling teardown_request() for the Flask application...')

    @app.teardown_appcontext
    def app_teardown_appcontext(error=None):
        app.logger.info(
            'Calling teardown_appcontext() for the Flask application...')

project/stocks/__init__.py
"""
The stocks blueprint handles the user management for this application.
Specifically, this blueprint allows for users to add, edit, and delete
stock data from their portfolio.
"""
from flask import Blueprint

stocks_blueprint = Blueprint('stocks', __name__, template_folder='templates')

from . import routes

project/stocks/routes.py
from . import stocks_blueprint
from flask import render_template, request, session, redirect, url_for, flash, current_app


@stocks_blueprint.route('/')
def index():
    current_app.logger.info('Calling the index() function.')
    return render_template('stocks/index.html')


@stocks_blueprint.route('/add_stock', methods=['GET', 'POST'])
def add_stock():
    if request.method == 'POST':
        # Save the form data to the session object
        session['stock_symbol'] = request.form['stock_symbol']
        session['number_of_shares'] = request.form['number_of_shares']
        session['purchase_price'] = request.form['purchase_price']
        flash(
            f"Added new stock ({ request.form['stock_symbol'] })!", 'success')
        current_app.logger.info(
            f"Added new stock ({ request.form['stock_symbol'] })!")
        # PREVIOUS: url_for('list_stocks')
        return redirect(url_for('stocks.list_stocks'))

    return render_template('stocks/add_stock.html')


@stocks_blueprint.route('/stocks')
def list_stocks():
    return render_template('stocks/stocks.html')

###########################
#### request callbacks ####
###########################


@stocks_blueprint.before_request
def stocks_before_request():
    current_app.logger.info(
        'Calling before_request() for the stocks blueprint...')


@stocks_blueprint.after_request
def stocks_after_request(response):
    current_app.logger.info(
        'Calling after_request() for the stocks blueprint...')
    return response


@stocks_blueprint.teardown_request
def stocks_teardown_request(error=None):
    current_app.logger.info(
        'Calling teardown_request() for the stocks blueprint...')

project/users/__init__.py
"""
The users Blueprint handles the user management for this application.
Specifically, this Blueprint allows for new users to register and for
users to log in and to log out of the application.
"""
from flask import Blueprint

users_blueprint = Blueprint('users', __name__, template_folder='templates')

from . import routes

project/users/routes.py
from . import users_blueprint
from flask import render_template, flash


@users_blueprint.route('/about')
def about():
    flash('Thanks for learning about this site!', 'info')
    return render_template('users/about.html', company_name='TestDriven.io')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flask Stock Portfolio App</title>
  
    <!-- Local CSS file for styling the application-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base_style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon">  <!-- NEW!! -->

      <!-- Additional Styling -->
      {% block styling %}
      {% endblock %}
  </head>

  <body>
    <header>
      <nav class="nav">
        <a class="nav-link logo" href="{{ url_for('stocks.index') }}">Flask Stock Portfolio App</a>
        <ul class="nav-list">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('stocks.list_stocks') }}">List Stocks</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('stocks.add_stock') }}">Add Stock</a></li>
        </ul>
      </nav>
    </header>


    <div class="messages">
      <!-- flash messages - supported categories: success, info, error, message (default) -->
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="flash-message flash-message-{{ category }}">
              <p>{{ message }}</p>
              <span class="close-btn" onclick="this.parentElement.style.opacity=0;">
                <svg width="12" height="12" version="1.1" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                  <path d="m49.941 35.891 33.531-33.531 14.168 14.168-33.531 33.414 33.531 33.531-14.168 14.168-33.531-33.531-33.414 33.531-14.168-14.168 33.531-33.531-33.531-33.414 14.168-14.168z" fill-rule="evenodd" fill="currentColor"/>
                </svg>
              </span>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
  
  
    <main class="content">
      <!-- child template -->
      {% block content %}
      {% endblock %}
    </main>
    <footer class="site-footer">
      <small>testdriven.io 2020</small>
    </footer>
  </body>
</html>